- Notes/Design.md
- Notes/Information.md
- Notes/Meetings.md
- Notes/Updates.md
Created a Notes folder where we can store project information, meeting notes, design notes and any updates/concerns.
> Notes folder creation

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/ProjectListingView/Components/ProjectTable/ProjectTable.js
Created a new Project Table component to view projects in a table.
> Create mock UI to view projects

- client/src/ProjectListingView/Components/ProjectTable/ProjectTable.js
1. Added status column with colours. It changes based on the project data:
**untouched**: no students interested 
**interested students:** some students ranked/liked/marked the project as interesting. 
**pending approval:** some groups applied for the project. 
**assigned:** prof assigned the project to a group. 
**students needed:** group is assigned, but more students can join the group.
2. Added dropdown **details** section to show interested students and project applications by group (for prof to approve). 
The "View Profile" button will eventually link to the student profile and the "View Application" button opens a modal to accept or reject a project application by a specific group.
3. Added columns with info that might be useful: 
**visibility**: if students can see or not …
> Expanded Professor View of Projects

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Added PR template and issue template so we have a defined structure when we create a new PR or issue
closes: #66
> Feat: Add PR template and Issue template

- client/src/ProjectListingView/Components/ProjectTable/ProjectTable.js
**Updates status:** changed "untouched" to "new". Also added a "proposed" project for groups to propose a new project. Here are the new states and the proposed state diagram for the workflow:
**Updated the Project Application modal:** 
- now has a _checkbox_ to be checked if the professor accepts, but wants more students (this will put the project in the "students needed" status). There's also a _tooltip_ that explains what it does if hovered over.
-  There's also a _feedback_ textfield if the professor wants to either only send feedback (using the "Send Feedback" button) or accept and send feedback.
> Modified status and added feedback text input for Projects

- docker-compose.yaml
- Missing $ means that the the env vars were not being passed to the container
-  Exec into the container and look at the env vars
- [NA ] Unit tests added/updated
- [ NA] Integration tests added/updated
> fix mongodb container

- scripts/runBackendLocally.sh
- server/app/models/student.py
> Adjust mongo

- client/src/App.js
- client/src/StaticComponents/NavBar/ResponsiveAppBar.js
- client/src/StudentListingView/StudentTable.js
Added a component that lists the students (the columns correspond to what is in the students-fake-list-SEG4910.csv that corresponds to the Import Student page). You can also add more students and export it.
https://github.com/umple/AcademicTeamManagement/issues/79
Run the front end and visually test it.
> Student List View

- .env
- docker-compose.yaml
- server/Dockerfile
- server/Pipfile.lock
- server/app/controllers/student_controller.py
- server/app/models/__init__.py
- fix the issue of mongodb volumes
- update the env variables
- app can run inside of a container and connect correctly to the DB
- ensure the tests still pass
closes: #77 
Run docker compose up and do some REST API calls
> Fix: MongoDB connection error with volumes

- client/src/HomePageView/StudentHomePage.js
Added new component that will be the student homepage
https://github.com/umple/AcademicTeamManagement/issues/62
Run frontend and see the component
> Created basic homepage for students

- server/app/models/__init__.py
- server/tests/unit/test_student.py
Currently, we're using the same database when we are testing our code. This is not recommended since we are inserting mockdata in our production db
> Fix: Adjust database for testing

- client/src/ProjectListingView/Components/ProjectTable/ProjectTable.js
- docker-compose.yaml
- init-db.js
- server/app/controllers/__init__.py
- server/app/controllers/project_controller.py
- server/app/controllers/student_controller.py
- server/app/models/__init__.py
- Fix mongodb in prod
- Fix env issues in docker-compose
- A lot more, I forgot
None
Just run it
- [NA ] Unit tests added/updated
- [ NA] Integration tests added/updated
> Fix issues on VM

- client/src/StudentListingView/StudentTable.js
Fixes bug that Akram noticed:
Go to Student page on local deploy and it doesn't crash
> Fix bug where column was null

- client/src/GroupView/GroupTable.js
- client/src/ProjectListingView/Components/ProjectTable/ProjectTable.js
- client/src/StudentListingView/StudentTable.js
There was a big in the export of excel files - data was not organized properly and mismatched to headers
The bug can be seen here http://159.89.49.26:3000/
> fix export

- server/app/utils/data_conversion.py
First Name and last name were not showing when importing due to unformatted keys
Before: http://159.89.49.26:3000/Students
Fix:
> Fixing Name not appearing in import

- client/package-lock.json
- client/package.json
- client/src/LoginView/LoginPage.js
> Login page similar to uottawa's

- client/package-lock.json
- client/src/StaticComponents/NavBar/ResponsiveAppBar.js
- server/Pipfile.lock
- server/security/auth.py
- Add logout button to the navbar
- Update API prefixes
closes: #116 
Try logging in then logout from the app
> Feat: Add Logout Functionality

- client/src/GroupView/GroupTable.js
- client/src/ProjectListingView/Components/ProjectTable/ProjectTable.js
- client/src/StudentListingView/StudentTable.js
- client/src/StudentView/StudentGroupTable.js
- client/src/StudentView/StudentProjects.js
- server/Pipfile.lock
fixed padding
also did shift + alt + f on the tables
closes: https://github.com/umple/AcademicTeamManagement/issues/101
open any of the affected tables in the issue
click the top element
no more padding
> fixed padding Issue 101

- client/src/App.js
- client/src/Authentication/PrivateRoutes.js
- server/security/auth.py
- Private routes Part 1
- Check if a user exists in the session
- Redirect the user if he/she doesn't exist yet
closes: #122 
- try to access one of the routes before login in, you should be redirected to the logging page
- if you are logged in and wants to use another route, you should not be redirected to the login page
> Feat: Check User is logged in

- client/src/App.js
- client/src/StaticComponents/PageNotFound/PageNotFound.js
- server/Pipfile.lock
- Added a PageNotFound component that redirects to all paths that don't match the endpoints we have
closes: #124 
Try to type a random URL that doesn't exist in the application
> Feat: Add a Page Not Found component

- client/src/App.js
- client/src/Authentication/RoleBasedRoutes.js
- client/src/Utils/Roles.js
- Students now can only access their pages, not the professor's
- Professors now can only access their pages, not the student's
closes: #126 
Try to access professor's page from the student's POV
> Feat: Add role based routes

- client/src/ProjectListingView/Components/ProjectTable/ProjectTable.js
- client/src/StudentView/MyGroup.js
- client/src/StudentView/StudentGroupTable.js
- client/src/StudentView/StudentProjects.js
- server/Pipfile.lock
- server/app/controllers/project_application_controller.py
- server/app/controllers/project_controller.py
- server/app/models/group.py
- server/app/models/project.py
- server/app/models/project_application.py
- server/main.py
> Connecting Project Application

- client/src/StudentView/MyGroup.js
> My Groups improvement

- client/src/GroupView/GroupTable.js
- client/src/ProjectListingView/Components/ProjectTable/ProjectTable.js
- server/app/controllers/group_controller.py
- server/app/controllers/project_application_controller.py
- server/app/controllers/project_controller.py
- server/app/controllers/student_controller.py
- server/app/models/group.py
- server/app/models/project.py
- server/app/models/project_application.py
- server/app/models/student.py
> fixed a lot

- scripts/package-lock.json
This file was created by mistake and is not necessary
> Fix: Delete the lcok file in scripts

- server/app/models/project.py
Error Works closes https://github.com/umple/AcademicTeamManagement/issues/130
> [Bug-fix] Project status

- client/src/Authentication/PrivateRoutes.js
- client/src/Utils/UserName.js
- client/src/Utils/UserType.js
> updated react calls

- client/src/StaticComponents/PageNotFound/PageNotFound.js
- server/app_config.py
- server/security/auth.py
> Fix: add `/getAToken` api extension

- client/src/App.js
- server/app/utils/auth_helpers.py
> Change Redirection

- client/src/ProjectListingView/Components/ProjectTable/ProjectTable.js
- scripts/runBackendLocally.sh
- server/app/models/project.py
> Issues 4-5 fixed

- client/src/GroupView/GroupTable.js
- client/src/ProjectListingView/Components/ProjectTable/ProjectTable.js
> Project selection is based on available projects

- client/src/StudentView/StudentProjects.js
Fix the 500 error got in the student view
> Fix: bug of empty projects

- client/src/StudentListingView/StudentTable.js
> Fix: extra columns for projects

- client/src/GroupView/GroupTable.js
- client/src/HomePageView/HomePage.js
- client/src/ImportStudentsView/ImportStudents.js
- client/src/LoginView/LoginPage.js
- client/src/ProjectListingView/Components/ProjectTable/ProjectTable.js
- client/src/StaticComponents/NavBar/ResponsiveAppBar.js
- client/src/StudentListingView/StudentTable.js
- client/src/StudentView/MyGroup.js
- client/src/StudentView/StudentGroupTable.js
- client/src/StudentView/StudentProjects.js
Fix console issues and errors from lint
> Fix: clean up console errors

- client/src/GroupView/GroupTable.js
- client/src/ProjectListingView/Components/ProjectTable/ProjectTable.js
- server/app/controllers/group_controller.py
- server/app/models/group.py
> Fix duplication key

- server/app/models/group.py
- server/app/models/student.py
- When a student gets deleted, it now removes him from a group. Before it just used to remove the student.
- Test it by removing a student that is in a group and see how it will remove him from the group
> Fix Student Deletion

- .github/workflows/scheduledBackup.yml
- README.md
> Mongo Backup procedure and cron job

- client/src/GroupView/GroupTable.js
- client/src/ProjectListingView/Components/ProjectTable/ProjectTable.js
- server/app/models/group.py
- server/app/models/project.py
- Projects with empty names cannot be added
- Projects with a name that already exists won't be added
- When a project is deleted, it is also unassigned from a group
-  
Test wtv is in the description
- [ x] PR/Change is verified in local dev environment
> Project edits

- client/src/ProjectListingView/Components/ProjectTable/ProjectTable.js
- client/src/StudentView/MyGroup.js
- client/src/StudentView/StudentProjects.js
- server/app/controllers/project_application_controller.py
- server/app/models/group.py
- server/app/models/project.py
- server/app/models/project_application.py
- server/app/models/student.py
> fixing project applications

- client/src/GroupView/GroupTable.js
- client/src/ProjectListingView/Components/ProjectTable/ProjectTable.js
> Fix applications

- client/src/ProjectListingView/Components/ProjectTable/ProjectTable.js
- client/src/StudentView/MyGroup.js
- client/src/Utils/statusColors.js
- client/src/services/api.js
Refactored Mygroup.js by creating modular components for re-used functions.  Also, made API calls async.
https://github.com/umple/AcademicTeamManagement/issues/178
Run front end locally.
> refactor Mygroup.js

- docs/progress/Meetings.md
Update Readme with meeting info
> update meeting minutes

- client/src/StudentView/AddProjectModal.js
- client/src/StudentView/StudentProjects.js
Created a new component for the modal and added a check that verifies if data obtained is not empty so it can be filtered (was producing an error).
https://github.com/umple/AcademicTeamManagement/issues/178
Run front end locally.
> refactor StudentProject.js

- client/src/StudentView/MyGroup.js
Quick fix for the students that don't have a group
Test locally
> Fix: Bug of the students that don't have groups

- client/src/components/ProjectTable/ProjectTable.js
the edit button looks new and works
pic unrelated
> Edit button style

- .github/workflows/test.yml
> Pipeline integration for react tests

- client/src/components/professorComponents/tables/StudentTable.js
- server/app/controllers/student_controller.py
- server/app/entities/ProjectEntity.py
- server/app/entities/StudentEntity.py
- server/app/models/student.py
Refactoring the student model
Updates for the controllers
Update for the finalGrade attribute
test locally
> Chore: Refactor Student model in the Backend

- client/src/components/studentsComponents/AddProjectModal.js
- client/src/components/studentsComponents/StudentProjects.js
- client/src/entities/Project.js
- client/src/pages/studentPages/StudentProjectPage.js
- client/src/schemas/projectSchema.js
When the student propose a group, the name of the project disappears, this PR fixes that bug
create a project as a student
> Fix: Name of the student's proposed project

- client/src/entities/Student.js
- client/src/tests/entities/Student.test.js
Fix the setters in Student component and provide full coverage for front-end testing.
https://github.com/umple/AcademicTeamManagement/issues/192
Run `npm test`
- [ x] PR/Change is verified in local dev environment
- [x ] Unit tests added/updated
> Finish testing front-end Student component

- server/tests/pipeline_tests/unit/test_project_model.py
Add tests for the project model
> Test: Add projects tests

- server/app/controllers/group_controller.py
- server/app/entities/GroupEntity.py
- server/app/models/group.py
- server/tests/pipeline_tests/unit/test_group_model.py
- refactore the group model to include GroupEntity
- add unit tests
> Chore: Refactor and Test Group entity

- client/cypress.config.js
- client/cypress/e2e/ProjectForm.cy.js
- client/cypress/fixtures/example.json
- client/cypress/support/commands.js
- client/cypress/support/e2e.js
- client/package-lock.json
- client/package.json
- client/src/components/common/ConfirmDeletionModal.js
- client/src/components/professorComponents/forms/ProjectForm.js
- client/src/components/professorComponents/tables/ProjectTable.js
- client/src/pages/LoginPage.js
> cypress tests

- server/app/models/project.py
- server/tests/pipeline_tests/unit/test_project_model.py
Improving test coverage to 98% for the project  model
> Test: More test cases for the Project model

- client/cypress/e2e/test.cy.js
- client/src/App.css
- client/src/components/professorComponents/tables/GroupTable.js
- client/src/components/professorComponents/tables/ProjectTable.js
- client/src/components/professorComponents/tables/StudentTable.js
- client/src/components/studentsComponents/StudentProjects.js
- client/src/components/studentsComponents/tables/StudentGroupTable.js
- client/src/pages/professorPages/HomePage.js
- server/app/controllers/group_controller.py
- server/app/controllers/project_controller.py
- server/app/controllers/student_controller.py
> Worked on professor home page dashboard 

- client/src/components/StaticComponents/NavBar/ResponsiveAppBar.js
These buttons didn't work
This PR fixes them so they work
> fixed shrunk navbar

- client/src/App.js
- client/src/components/StaticComponents/NavBar/ResponsiveAppBar.js
- client/src/components/professorComponents/tables/GroupTable.js
- client/src/components/professorComponents/tables/ProjectTable.js
- client/src/components/professorComponents/tables/StudentTable.js
- client/src/helpers/Roles.js
- client/src/pages/adminPages/AdminHomePage.js
- server/app/utils/auth_helpers.py
Add a new role "ADMIN"
allow the admin to view all data
> Feat: Add admin role

- client/src/App.js
- client/src/components/StaticComponents/NavBar/ResponsiveAppBar.js
- client/src/components/professorComponents/forms/SectionForm.js
- client/src/components/professorComponents/tables/SectionTable.js
- client/src/components/professorComponents/tables/styles/SectionTableStyles.js
- client/src/entities/Section.js
- client/src/pages/professorPages/ProfessorSectionPage.js
- client/src/schemas/sectionSchema.js
- client/src/services/sectionService.js
Create section for course Sections
> add course section to ui

- server/app/controllers/__init__.py
- server/app/controllers/section_controller.py
- server/app/entities/SectionEntity.py
- server/app/models/section.py
- server/main.py
> Feat: Add sections to backend

- client/src/components/common/ConfirmDeletionModal.js
- client/src/components/professorComponents/forms/SectionForm.js
- client/src/components/professorComponents/tables/SectionTable.js
- client/src/schemas/sectionSchema.js
Fetch sections from database
Few improvements
> Feat: Integrate changes for sections

- client/src/App.js
- client/src/components/StaticComponents/NavBar/ResponsiveAppBar.js
- client/src/components/adminComponents/forms/StaffForm.js
- client/src/components/adminComponents/tables/StaffTable.js
- client/src/components/adminComponents/tables/styles/StaffTableStyles.js
- client/src/components/common/ConfirmDeletionModal.js
- client/src/components/studentsComponents/MyGroup.js
- client/src/entities/Staff.js
- client/src/helpers/UserType.js
- client/src/pages/adminPages/AdminHomePage.js
- client/src/pages/adminPages/AdminStaffPage.js
- client/src/pages/professorPages/HomePage.js
- client/src/schemas/staffSchema.js
- client/src/services/staffService.js
- server/app/controllers/__init__.py
- server/app/controllers/staff_controller.py
- server/app/controllers/student_controller.py
- server/app/controllers/user_controller.py
- server/app/entities/StaffEntity.py
- server/app/entities/StudentEntity.py
- server/app/entities/UserEntity.py
- server/app/models/staff.py
- server/app/models/student.py
- server/app/models/user.py
- server/main.py
- Added a new navbar item for the admin that shows staff
- staff includes professors and admins
- admin can now creates profs and other admins
- update the role of all users
- create new entities User and Staff
- few bug fixes
> Feat: Add Staff section to admin

- client/src/components/studentsComponents/tables/StudentGroupTable.js
Added a "Create Group" button
Run the ui
> add group button to student view

- server/app/models/user.py
- server/security/auth.py
For existing users in Azure, we need to skip the part of checking them as users
> Fix: issue with null users

- client/src/components/professorComponents/ImportStudents.js
- server/app/controllers/student_controller.py
Allow professor to specify the section when importing
> Feat: Add section to import

- client/src/components/professorComponents/tables/GroupTable.js
- client/src/components/professorComponents/tables/ProjectTable.js
- client/src/components/professorComponents/tables/SectionTable.js
- client/src/components/professorComponents/tables/StudentTable.js
- client/src/components/studentsComponents/StudentProjects.js
- client/src/pages/adminPages/AdminHomePage.js
- client/src/pages/professorPages/HomePage.js
> Fix all possible bugs

- client/src/components/studentsComponents/forms/StudentGroupForm.js
- client/src/components/studentsComponents/tables/StudentGroupTable.js
> Add functionality to create a group

- client/src/components/studentsComponents/MyGroup.js
- client/src/components/studentsComponents/StudentProjects.js
- client/src/components/studentsComponents/forms/AddProjectModal.js
- client/src/components/studentsComponents/forms/StudentGroupForm.js
- client/src/components/studentsComponents/tables/StudentGroupTable.js
- client/src/pages/studentPages/StudentHomePage.js
- client/src/schemas/createGroupSchema.js
- client/src/schemas/projectSchema.js
- client/src/schemas/studentSchema.js
- client/src/services/groupService.js
- client/src/services/studentService.js
- server/app/controllers/group_controller.py
- server/app/controllers/student_controller.py
- server/app/models/student.py
- server/tests/pipeline_tests/unit/test_student_model.py
fixing bugs in the group table of students when joining or leaving a group
> Fix: Group student bugs

- client/src/locales/en/translation.json
- client/src/locales/fr/translation.json
- client/src/pages/adminPages/AdminHomePage.js
- client/src/pages/professorPages/HomePage.js
- client/src/pages/studentPages/StudentHomePage.js
Translated strings in home pages
> translate home pages

- project management/deliverables/deliverable_3/weekly_minutes/week2.md
> update weekly meeting minutes

- client/src/components/studentsComponents/ProjectCard.js
- client/src/components/studentsComponents/StudentProjects.js
- client/src/components/studentsComponents/forms/AddProjectModal.js
- client/src/components/studentsComponents/styles/AddProjectModalStyles.js
- client/src/components/studentsComponents/styles/StudentProjectStyles.js
> Fix student view

- client/cypress/e2e/GroupForm.cy.js
- client/cypress/e2e/ProjectForm.cy.js
- client/src/components/professorComponents/forms/EditGroupModal.js
- client/src/components/professorComponents/forms/GroupForm.js
- client/src/components/professorComponents/tables/GroupTable.js
- client/src/components/studentsComponents/ProjectCard.js
- client/src/components/studentsComponents/StudentProjects.js
- client/src/components/studentsComponents/forms/AddProjectModal.js
- client/src/entities/Project.js
- client/src/schemas/professorProjectSchema.js
- client/src/schemas/projectSchema.js
- client/src/services/groupService.js
- server/app/controllers/group_controller.py
- server/app/models/group.py
> Fix: Issues related to groups

- server/app/controllers/section_controller.py
- server/app/models/section.py
- server/app/models/student.py
Problem 2, section name updated should also update the section for all students
> Fix: Section name should be updated for students

- client/src/components/professorComponents/tables/StudentTable.js
> fix: problem 14 add group to student table

- server/app/controllers/student_controller.py
- server/app/models/student.py
- server/tests/pipeline_tests/unit/test_student_model.py
There was an issue with importing students, where we didn't add the users
> Fix: Import issues for students

- server/app/models/group.py
> Fix: The edit group should update the students in it too

- client/src/components/professorComponents/forms/EditGroupModal.js
- client/src/services/groupService.js
- server/app/controllers/group_controller.py
- server/app/models/group.py
We now have a button that clears all group members from the group
> Fix: Remove students from group

- client/src/components/professorComponents/forms/EditStudentModal.js
- client/src/components/professorComponents/forms/StudentForm.js
- client/src/schemas/createGroupSchema.js
- client/src/schemas/sectionSchema.js
- client/src/schemas/staffSchema.js
- client/src/schemas/studentSchema.js
Another bug when we have empty lists, this is due to the .find function in the schemas, we need to check for that error.
Update the modals for the student to remove the group part, we don't want to modify it from the student table
> Fix: Few bug fixes for the schemas

- client/src/components/common/ConfirmDeletionModal.js
- client/src/components/professorComponents/tables/ProjectTable.js
- client/src/components/professorComponents/tables/StudentTable.js
- client/src/services/studentService.js
- server/app/controllers/student_controller.py
- server/app/models/student.py
> WIP: just need to have the rows reload after deleting all students

- client/src/components/professorComponents/forms/EditProjectForm.js
- client/src/components/professorComponents/forms/ProjectForm.js
- client/src/components/professorComponents/tables/ProjectTable.js
- client/src/components/studentsComponents/StudentProjects.js
- client/src/components/studentsComponents/forms/AddProjectModal.js
- client/src/schemas/professorProjectSchema.js
- client/src/schemas/projectSchema.js
Make the project name unique for both professors and students
> Fix: Make the project Name unique

- client/src/components/adminComponents/forms/StaffForm.js
- client/src/components/professorComponents/ImportStudents.js
- client/src/components/professorComponents/ViewApplicationModal.js
- client/src/components/professorComponents/forms/EditGroupModal.js
- client/src/components/professorComponents/forms/EditProjectForm.js
- client/src/components/professorComponents/forms/EditStudentModal.js
- client/src/components/professorComponents/forms/GroupForm.js
- client/src/components/professorComponents/forms/ProjectForm.js
- client/src/components/professorComponents/forms/SectionForm.js
- client/src/components/professorComponents/forms/StudentForm.js
- client/src/components/studentsComponents/forms/AddProjectModal.js
- client/src/components/studentsComponents/forms/StudentGroupForm.js
> Chore: Updates for the typography

- client/src/components/studentsComponents/MyGroup.js
- client/src/locales/en/translation.json
- client/src/locales/fr/translation.json
All strings and table is translated:
https://github.com/orgs/umple/projects/2/views/1?pane=issue&itemId=44186196
> translate MyGroup page

- client/src/components/professorComponents/forms/SectionForm.js
- client/src/components/professorComponents/tables/SectionTable.js
- client/src/locales/en/translation.json
- client/src/locales/fr/translation.json
despite the branch being called prof translation this translates sections
also it translates a few common words like save and delete
> added translation for sections

- server/security/azure.py
The redirect URL is set incorrectly
> Fix: Fix the redirect issue

- client/src/components/professorComponents/ViewApplicationModal.js
- client/src/components/professorComponents/forms/ProjectForm.js
- client/src/components/professorComponents/tables/ProjectTable.js
- client/src/components/studentsComponents/MyGroup.js
- client/src/locales/en/translation.json
- client/src/locales/fr/translation.json
- client/src/services/projectService.js
- server/app/controllers/project_application_controller.py
- server/app/models/project_application.py
A lot of bugs fixes for project applications when being modified
Students can now rank their projects
Review application modal is updated
compared to the old modal
closes: https://github.com/umple/AcademicTeamManagement/issues/21
> Fix: Projects applications bugs

- server/security/auth.py
Handle redirection of non existing users
> Chore: Redirect non exisiting users

- client/src/components/studentsComponents/StudentProjects.js
> Chore: Fix styling for the projects search bar

- client/src/components/professorComponents/forms/MoveStudentsModal.js
- client/src/components/professorComponents/tables/StudentTable.js
- client/src/locales/en/translation.json
- client/src/locales/fr/translation.json
- client/src/services/studentService.js
- server/app/controllers/student_controller.py
- server/app/models/group.py
- server/app/models/student.py
New button can be seen here
And the modal here
> Feat: Adding button to change the group of Students

- client/src/components/StaticComponents/NavBar/ResponsiveAppBar.js
Make sure that the language selected is persisted and does not change when the page is switched or reloaded
closes: #263
> Chore: Add caching to the language selected

- client/src/components/adminComponents/tables/StaffTable.js
- client/src/components/professorComponents/tables/GroupTable.js
- client/src/components/professorComponents/tables/ProjectTable.js
- client/src/components/professorComponents/tables/SectionTable.js
- client/src/components/professorComponents/tables/StudentTable.js
- client/src/components/studentsComponents/MyGroup.js
- client/src/components/studentsComponents/tables/StudentGroupTable.js
> Chore: Set pagination to 200 for the tables

- .github/workflows/test.yml
- client/package.json
- client/src/components/adminComponents/tables/StaffTable.js
- client/src/components/professorComponents/tables/GroupTable.js
- client/src/components/professorComponents/tables/ProjectTable.js
- client/src/components/professorComponents/tables/SectionTable.js
- client/src/components/professorComponents/tables/StudentTable.js
- client/src/helpers/Constants.js
- client/src/locales/en/translation.json
- client/src/locales/fr/translation.json
I set it to 5 rows just to show the button, but it will only appear when there are more than 200 rows
> Feat: Add button to expend page size

- client/src/components/professorComponents/forms/GroupForm.js
- client/src/components/professorComponents/tables/GroupTable.js
- client/src/components/studentsComponents/tables/StudentGroupTable.js
- client/src/locales/en/translation.json
- client/src/locales/fr/translation.json
> translate group pages

- client/src/pages/adminPages/AdminHomePage.js
- client/src/pages/professorPages/HomePage.js
> update card design

- client/src/components/professorComponents/forms/GroupForm.js
- client/src/components/professorComponents/tables/GroupTable.js
- client/src/components/professorComponents/tables/ProjectTable.js
- client/src/schemas/createGroupSchema.js
> Chore: Add redirection to group table

- client/src/components/adminComponents/forms/StaffForm.js
- client/src/components/professorComponents/forms/GroupForm.js
- client/src/components/professorComponents/forms/ProjectForm.js
- client/src/components/professorComponents/forms/SectionForm.js
- client/src/components/professorComponents/forms/StudentForm.js
- client/src/components/professorComponents/tables/ProjectTable.js
- client/src/locales/en/translation.json
- client/src/locales/fr/translation.json
> Chore: Add screen loading

- project management/deliverables/deliverable_3/executive_summary.md
> add deliverable 3 links

- client/src/pages/professorPages/HomePage.js
> Fix: Filter the data by prof

- client/src/components/professorComponents/forms/SectionForm.js
- client/src/components/studentsComponents/StudentProjects.js
- The creat section should not show the lock status
- fixes for the projects table styling
> Fix: Section lock switch

- client/src/components/professorComponents/ViewApplicationModal.js
- client/src/components/professorComponents/tables/ProjectTable.js
- client/src/components/studentsComponents/MyGroup.js
- client/src/components/studentsComponents/ProjectCard.js
- client/src/components/studentsComponents/tables/StudentGroupTable.js
- client/src/locales/en/translation.json
- client/src/locales/fr/translation.json
- server/app/controllers/group_controller.py
- server/app/controllers/project_application_controller.py
- server/app/models/group.py
- server/app/models/project.py
- server/app/models/project_application.py
- Bug fix for linking between modified group name and its corresponding project.
- Allow the professor to see newly submitted project requests by highlighting the row in the table, by clicking on the "Show New Requests" button on the Project Page
- If there is only one student left in the group, don't allow them to leave the group otherwise we will be stuck with an empty group
- If a project application gets accepted, other applications to the project will be sent to "Rejected"
- When a group gets deleted, remove its project applications
> Fix: Bugs with groups and applications

- client/src/App.js
- client/src/components/StaticComponents/NavBar/ResponsiveAppBar.js
- client/src/components/adminComponents/forms/StaffForm.js
- client/src/components/adminComponents/tables/StaffTable.js
- client/src/components/professorComponents/forms/GroupForm.js
- client/src/components/professorComponents/forms/MoveStudentsModal.js
- client/src/components/professorComponents/forms/ProjectForm.js
- client/src/components/professorComponents/forms/StudentForm.js
- client/src/components/professorComponents/tables/GroupTable.js
- client/src/components/professorComponents/tables/ProjectTable.js
- client/src/components/professorComponents/tables/SectionTable.js
- client/src/components/professorComponents/tables/StudentTable.js
- client/src/entities/Staff.js
- client/src/helpers/GetProfessorEmail.js
- client/src/helpers/Roles.js
- client/src/helpers/UserEmail.js
- client/src/helpers/UserLinkedProfessor.js
- client/src/locales/en/translation.json
- client/src/locales/fr/translation.json
- client/src/pages/professorPages/HomePage.js
- server/app/controllers/user_controller.py
- server/app/entities/StaffEntity.py
- server/app/utils/auth_helpers.py
Added a new role TA
- TAs are linked with a specific professor
- TAs can add/update/delete the student/groups/projects data
- TAs check sections but cannot create/update/delete them
- TAs can add students but cannot import them
> Feat: Add a TA role

- client/src/components/professorComponents/forms/EditGroupModal.js
- client/src/components/professorComponents/forms/GroupForm.js
- client/src/components/professorComponents/tables/GroupTable.js
- client/src/services/groupService.js
- server/app/controllers/group_controller.py
- server/app/models/group.py
Add a button that enables professors to be redirected to the teams chat of the group
Button is at the far right
https://github.com/umple/AcademicTeamManagement/issues/313
> Feat: Add teams group chat

- client/src/components/studentsComponents/MyGroup.js
- server/app/models/project_application.py
This PR adds a feature to allow the students to remove their applications
Students cannot remove their application if it's set to Accepted or Rejected
> Feat: Allow students to remove applications

- client/src/components/studentsComponents/ProjectCard.js
- docs/devops/RELEASE.md
Students with an empty group should not be able to request a project
Adding Release notes
> Fix: Bug for student requests

- server/app/models/group.py
> fixed crashing issue

- client/src/helpers/UserType.js
- server/app/controllers/user_controller.py
> hotfix for professor logon issues
